import type { NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button";
import { useContext, useState } from "react";
import "@biconomy/web3-auth/dist/src/style.css";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import dynamic from "next/dynamic";
import Loading from "../components/Loading";
import Modal from "../components/Modal";
import { getUserInfo } from "../lib/api-helpers/user-api";
import { UserRoleContext } from "../contexts/UserRoleProvider";
import useSWR from "swr";
import Image from "next/image";
import CustomLink from "../components/CustomLink";
import { CheckCircleIcon } from "@heroicons/react/20/solid";
import TabGroupBordered from "../components/TabGroupBordered";
import CardSwiper from "../components/LandingPage/CardSwiper";
import {
  analyticsCards,
  communityCards,
  eventCards,
  merchandiseCards,
  profileCards,
} from "../utils/landingPageCardsData";

function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(" ");
}

const HomePage: NextPage = () => {
  const router = useRouter();
  const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);
  const [activeTab, setActiveTab] = useState(0);

  const { data: session, status } = useSession();
  const userId = session?.user.userId;

  const { isFan } = useContext(UserRoleContext);
  // const { data: userData, error, isLoading } = useSWR(userId, getUserInfo);

  const SocialLoginDynamic = dynamic(
    () => import("../components/scw").then((res) => res.default),
    {
      ssr: false,
      loading: () => <Loading className="!h-full" />,
    }
  );

  // if (isLoading) {
  //   return <Loading />;
  // }

  return (
    <div className="debug-screens">
      <Head>
        <title>Home | Connexus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <nav className="mx-auto flex max-w-7xl justify-center bg-white px-8 pt-4 md:justify-between">
          <div className="md:hidden">
            <Image
              src="/svgs/mobile-connexus-logo.svg"
              alt="Connexus logo"
              width={35}
              height={35}
            />
          </div>
          <div className="hidden md:block">
            <Image
              src="/svgs/desktop-connexus-logo.svg"
              alt="Connexus logo"
              width={160}
              height={50}
            />
          </div>
          <div className="hidden md:flex md:gap-x-4 md:font-medium md:text-blue-500">
            <CustomLink className="hover:text-blue-400" href="#product">
              Product
            </CustomLink>
            <CustomLink className="hover:text-blue-400" href="#about-us">
              About Us
            </CustomLink>
          </div>
        </nav>

        {/* main hero section */}
        <div className="relative bg-sky-100">
          <div className="mx-auto mt-8 max-w-7xl px-8 pt-4 lg:flex lg:gap-20 lg:py-40">
            {/* mobile hero section */}
            <section className="mx-auto mt-8 max-w-7xl">
              <h1 className="mb-4 text-3xl font-bold">
                Grow your authentic relationships with your fans through
                Connexus.
              </h1>
              <p className="pb-4 font-semibold text-gray-500">
                All-in-one platform to empower creators to develop authentic
                relationships with their fans.
              </p>
              <ul className="flex flex-col gap-y-3 py-4 text-gray-500">
                <li className="flex gap-x-2">
                  <CheckCircleIcon className="h-5 w-5 text-blue-500" />
                  NFT-powered Digital Ticket/Merchandise
                </li>
                <li className="flex gap-x-2">
                  <CheckCircleIcon className="h-5 w-5 text-blue-500" />
                  Transparent Marketplace
                </li>
                <li className="flex gap-x-2">
                  <CheckCircleIcon className="h-5 w-5 text-blue-500" />
                  Social Channels for Fan Engagement
                </li>
                <li className="flex gap-x-2">
                  <CheckCircleIcon className="h-5 w-5 text-blue-500" />
                  Fan Behavior Analytics
                </li>
              </ul>
            </section>

            {/* Join our community section */}
            <section className="mx-auto max-w-7xl pt-20">
              <div className="relative flex flex-col items-center justify-center rounded-2xl border border-gray-100 bg-white p-8 shadow-md lg:w-80">
                <div className="absolute -top-8 rounded-2xl bg-blue-300 p-4">
                  <Image
                    src="/svgs/mobile-connexus-logo.svg"
                    alt="Connexus logo"
                    width={35}
                    height={35}
                  />
                </div>
                <h2 className="mt-8 text-2xl font-bold">Join our community</h2>
                <div className="mb-8 flex flex-wrap gap-4">
                  <Button
                    variant="solid"
                    size="md"
                    className="mt-4 px-20"
                    // onClick={
                    //   session
                    //     ? isFan
                    //       ? () => router.push("/communities")
                    //       : userData.createdCommunities.length > 0
                    //       ? () =>
                    //           router.push(
                    //             `/communities/${userData.createdCommunities[0].communityId}`
                    //           )
                    //       : () => router.push("/communities/create")
                    //     : () => setIsAuthModalOpen(true)
                    // }
                  >
                    Login
                  </Button>
                  <Modal
                    isOpen={isAuthModalOpen}
                    setIsOpen={setIsAuthModalOpen}
                  >
                    <SocialLoginDynamic isAuthModalOpen={isAuthModalOpen} />
                  </Modal>
                </div>
              </div>
            </section>
          </div>
          <div className="absolute -bottom-20 w-full">
            <Image
              src="/images/landing-bg-wave.png"
              alt="wave image"
              width={3000}
              height={500}
              // fill
            />
          </div>
        </div>

        {/* Explore our product section */}
        <section className="mx-auto max-w-7xl px-8 pt-32 lg:py-40">
          <h2 className="text-center text-2xl font-semibold lg:text-left">
            Explore our product
          </h2>
          <p className="mt-4 text-center text-gray-500 lg:text-left">
            Manage every aspect of your authentic relationships with your fans
            in one secure platform.
          </p>
          <TabGroupBordered
            tabs={[
              "Events",
              "Community",
              "Merchandise",
              "Analytics",
              "Profile",
            ]}
            activeTab={activeTab}
            setActiveTab={(index: number) => {
              setActiveTab(index);
            }}
          >
            {activeTab == 0 && <CardSwiper cards={eventCards} />}
            {activeTab == 1 && <CardSwiper cards={communityCards} />}
            {activeTab == 2 && <CardSwiper cards={merchandiseCards} />}
            {activeTab == 3 && <CardSwiper cards={analyticsCards} />}
            {activeTab == 4 && <CardSwiper cards={profileCards} />}
          </TabGroupBordered>
        </section>

        {/* About us section */}
        <section className="bg-gradient-to-b from-[#87DBFF] via-blue-100 to-white">
          <div className={classNames("mx-auto max-w-7xl px-4 pt-16 lg:py-40")}>
            <h2 className="text-center text-2xl font-semibold">About us</h2>
            <p className="py-8 text-center text-3xl font-extrabold leading-[3.5rem] tracking-wider lg:text-5xl lg:leading-[4.5rem]">
              Our Mission is to empower creators to{" "}
              <span className="text-blue-500">
                develop authentic relationships
              </span>{" "}
              with their fans.
            </p>
          </div>
        </section>

        {/* Misc section */}
        <section className="mx-auto max-w-7xl px-8 pt-8">
          <div className="flex flex-col lg:flex-row lg:items-center lg:gap-x-12">
            <div className="text-center lg:text-left">
              <h3 className="text-2xl font-semibold">
                How Connexus came about
              </h3>
              <p className="py-4 text-gray-500">
                The idea for Connexus originated in 2023, when our founding
                members sought to provide a common channel of outreach between
                creators and fans, be it through events, merchandise or even
                social communities to interact together.
              </p>
            </div>
            <div className="rounded-md p-4 shadow-lg transition-all duration-300 hover:shadow-2xl">
              <video width="1200" autoPlay loop>
                <source
                  src="/videos/connexus-landing-demo-one.mp4"
                  type="video/mp4"
                />
                Your browser does not support the video tag.
              </video>
            </div>
          </div>

          <div className="mt-12 flex flex-col lg:flex-row-reverse lg:items-center lg:gap-x-12">
            <div className="text-center lg:text-left">
              <h3 className="text-2xl font-semibold">How we drive value</h3>
              <p className="py-4 text-gray-500">
                Using blockchain technology,Connexus enables the exchange of
                event tickets and digital merchandise, a token-gated community
                channel exclusive to creators and fans to be transparent and the
                traceability of data shared across a business network. 
              </p>
            </div>
            <div className="rounded-md p-4 shadow-lg transition-all duration-300 hover:shadow-2xl">
              <video width="800" height="800" autoPlay loop>
                <source
                  src="/videos/connexus-landing-demo-two.mp4"
                  type="video/mp4"
                />
                Your browser does not support the video tag.
              </video>
            </div>
          </div>
        </section>

        <footer className="mt-20 flex flex-col items-center gap-y-4 bg-sky-100 py-4 pt-8">
          <div className="">
            <Image
              src="/svgs/desktop-connexus-logo.svg"
              alt="Connexus logo"
              width={140}
              height={50}
            />
          </div>
          <p className="text-center text-gray-500">
            For Creators to Develop Authentic Relationships with Their Fans.
          </p>
          <p className="text-xs text-gray-500">
            © 2023 Connexus. All rights reserved.
          </p>
        </footer>
      </main>
    </div>
  );
};

export default HomePage;
